[build]
target = "x86_64-pc-windows-msvc"
rustflags = [
    "-C", "debuginfo=0",
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "strip=symbols",
    "-C", "panic=immediate-abort",
    "-Z", "unstable-options",
    "-Z", "panic_abort_tests",
    "-Z", "location-detail=none",
    "-Z", "fmt-debug=none",
    "-C", "linker=lld-link",
    "-C", "lto=thin",
    "-C", "embed-bitcode=yes",
    "-C", "default-linker-libraries=yes",
    "-C", "relocation-model=static",
    "-C", "link-arg=/OPT:REF",
    "-C", "link-arg=/OPT:ICF",
    "-C", "target-feature=+crt-static",
]

[unstable]
build-std = ["std"]

[alias]
b-static-nvidia = [
    "build",
    "--release",
    "--no-default-features",
    "--features", "vship,cuda,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=0', '-C', 'target-cpu=native', '-C', 'opt-level=3', '-C', 'codegen-units=1', '-C', 'strip=symbols', '-C', 'panic=immediate-abort', '-Z', 'unstable-options', '-C', 'linker=lld-link', '-C', 'lto=thin', '-C', 'embed-bitcode=yes', '-C', 'default-linker-libraries=yes', '-C', 'relocation-model=static', '-Z', 'panic_abort_tests', '-Z', 'location-detail=none', '-Z', 'fmt-debug=none', '-C', 'target-feature=+crt-static', '-C', 'link-arg=/OPT:REF', '-C', 'link-arg=/OPT:ICF']"
]

r-static-nvidia = [
    "run",
    "--release",
    "--no-default-features",
    "--features", "vship,cuda,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=0', '-C', 'target-cpu=native', '-C', 'opt-level=3', '-C', 'codegen-units=1', '-C', 'strip=symbols', '-C', 'panic=immediate-abort', '-Z', 'unstable-options', '-C', 'linker=lld-link', '-C', 'lto=thin', '-C', 'embed-bitcode=yes', '-C', 'default-linker-libraries=yes', '-C', 'relocation-model=static', '-Z', 'panic_abort_tests', '-Z', 'location-detail=none', '-Z', 'fmt-debug=none', '-C', 'target-feature=+crt-static', '-C', 'link-arg=/OPT:REF', '-C', 'link-arg=/OPT:ICF']"
]

c-static-nvidia = [
    "check",
    "--release",
    "--no-default-features",
    "--features", "vship,cuda,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=0', '-C', 'target-cpu=native', '-C', 'opt-level=3', '-C', 'codegen-units=1', '-C', 'strip=symbols', '-C', 'panic=immediate-abort', '-Z', 'unstable-options', '-C', 'linker=lld-link', '-C', 'lto=thin', '-C', 'embed-bitcode=yes', '-C', 'default-linker-libraries=yes', '-C', 'relocation-model=static', '-Z', 'panic_abort_tests', '-Z', 'location-detail=none', '-Z', 'fmt-debug=none', '-C', 'target-feature=+crt-static', '-C', 'link-arg=/OPT:REF', '-C', 'link-arg=/OPT:ICF']"
]

d-static-nvidia = [
    "build",
    "--no-default-features",
    "--features", "vship,cuda,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=2', '-C', 'target-cpu=native', '-C', 'force-frame-pointers=yes', '-C', 'linker=lld-link', '-C', 'target-feature=+crt-static']"
]

b-static-amd = [
    "build",
    "--release",
    "--no-default-features",
    "--features", "vship,amd,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=0', '-C', 'target-cpu=native', '-C', 'opt-level=3', '-C', 'codegen-units=1', '-C', 'strip=symbols', '-C', 'panic=immediate-abort', '-Z', 'unstable-options', '-C', 'linker=lld-link', '-C', 'lto=thin', '-C', 'embed-bitcode=yes', '-C', 'default-linker-libraries=yes', '-C', 'relocation-model=static', '-Z', 'panic_abort_tests', '-Z', 'location-detail=none', '-Z', 'fmt-debug=none', '-C', 'target-feature=+crt-static', '-C', 'link-arg=/OPT:REF', '-C', 'link-arg=/OPT:ICF']"
]

r-static-amd = [
    "run",
    "--release",
    "--no-default-features",
    "--features", "vship,amd,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=0', '-C', 'target-cpu=native', '-C', 'opt-level=3', '-C', 'codegen-units=1', '-C', 'strip=symbols', '-C', 'panic=immediate-abort', '-Z', 'unstable-options', '-C', 'linker=lld-link', '-C', 'lto=thin', '-C', 'embed-bitcode=yes', '-C', 'default-linker-libraries=yes', '-C', 'relocation-model=static', '-Z', 'panic_abort_tests', '-Z', 'location-detail=none', '-Z', 'fmt-debug=none', '-C', 'target-feature=+crt-static', '-C', 'link-arg=/OPT:REF', '-C', 'link-arg=/OPT:ICF']"
]

c-static-amd = [
    "check",
    "--release",
    "--no-default-features",
    "--features", "vship,amd,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=0', '-C', 'target-cpu=native', '-C', 'opt-level=3', '-C', 'codegen-units=1', '-C', 'strip=symbols', '-C', 'panic=immediate-abort', '-Z', 'unstable-options', '-C', 'linker=lld-link', '-C', 'lto=thin', '-C', 'embed-bitcode=yes', '-C', 'default-linker-libraries=yes', '-C', 'relocation-model=static', '-Z', 'panic_abort_tests', '-Z', 'location-detail=none', '-Z', 'fmt-debug=none', '-C', 'target-feature=+crt-static', '-C', 'link-arg=/OPT:REF', '-C', 'link-arg=/OPT:ICF']"
]

d-static-amd = [
    "build",
    "--no-default-features",
    "--features", "vship,amd,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=2', '-C', 'target-cpu=native', '-C', 'force-frame-pointers=yes', '-C', 'linker=lld-link', '-C', 'target-feature=+crt-static']"
]

b-static-vulkan = [
    "build",
    "--release",
    "--no-default-features",
    "--features", "vship,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=0', '-C', 'target-cpu=native', '-C', 'opt-level=3', '-C', 'codegen-units=1', '-C', 'strip=symbols', '-C', 'panic=immediate-abort', '-Z', 'unstable-options', '-C', 'linker=lld-link', '-C', 'lto=thin', '-C', 'embed-bitcode=yes', '-C', 'default-linker-libraries=yes', '-C', 'relocation-model=static', '-Z', 'panic_abort_tests', '-Z', 'location-detail=none', '-Z', 'fmt-debug=none', '-C', 'target-feature=+crt-static', '-C', 'link-arg=/OPT:REF', '-C', 'link-arg=/OPT:ICF']"
]

r-static-vulkan = [
    "run",
    "--release",
    "--no-default-features",
    "--features", "vship,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=0', '-C', 'target-cpu=native', '-C', 'opt-level=3', '-C', 'codegen-units=1', '-C', 'strip=symbols', '-C', 'panic=immediate-abort', '-Z', 'unstable-options', '-C', 'linker=lld-link', '-C', 'lto=thin', '-C', 'embed-bitcode=yes', '-C', 'default-linker-libraries=yes', '-C', 'relocation-model=static', '-Z', 'panic_abort_tests', '-Z', 'location-detail=none', '-Z', 'fmt-debug=none', '-C', 'target-feature=+crt-static', '-C', 'link-arg=/OPT:REF', '-C', 'link-arg=/OPT:ICF']"
]

c-static-vulkan = [
    "check",
    "--release",
    "--no-default-features",
    "--features", "vship,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=0', '-C', 'target-cpu=native', '-C', 'opt-level=3', '-C', 'codegen-units=1', '-C', 'strip=symbols', '-C', 'panic=immediate-abort', '-Z', 'unstable-options', '-C', 'linker=lld-link', '-C', 'lto=thin', '-C', 'embed-bitcode=yes', '-C', 'default-linker-libraries=yes', '-C', 'relocation-model=static', '-Z', 'panic_abort_tests', '-Z', 'location-detail=none', '-Z', 'fmt-debug=none', '-C', 'target-feature=+crt-static', '-C', 'link-arg=/OPT:REF', '-C', 'link-arg=/OPT:ICF']"
]

d-static-vulkan = [
    "build",
    "--no-default-features",
    "--features", "vship,avm",
    "--config",
    "build.rustflags=['-C', 'debuginfo=2', '-C', 'target-cpu=native', '-C', 'force-frame-pointers=yes', '-C', 'linker=lld-link', '-C', 'target-feature=+crt-static']"
]
